export const robots =[
{
	id: 1,
	name: 'Olawale Olayefa',
	username: 'Monterro',
	email: 'olawaleyefa@gmail.com',
},
{
	id: 2,
	name: 'Adeboye Emmnauel',
	username: 'Thomas',
	email: 'ademanuel@gmail.com',
},
{
	id: 3,
	name: 'Adeyemi John',
	username: 'vaquita',
	email: 'vaquitatech@gmail.com',
},
{
	id: 4,
	name: 'Adebayo Olamuyiwa',
	username: 'Bostons',
	email: 'muyiwabayo@gmail.com',
},
{
	id: 5,
	name: 'Adebola Adeola',
	username: 'Monterro',
	email: 'olawaleyefa@gmail.com',
},
{
	id: 6,
	name: 'Adeyanju Abimbola',
	username: 'Business',
	email: 'buyersales@gmail.com',
},
{
	id: 7,
	name: 'Pius Timothy',
	username: 'Blacklisted',
	email: 'Blacklisted@gmail.com',
},
{
	id: 8,
	name: 'Adijat Adebayo',
	username: 'Oritoke',
	email: 'adijatoritoke@gmail.com',
},
{
	id: 9,
	name: 'Muhammed Musa',
	username: 'Madhuka',
	email: 'hammedhukza@gmail.com',
},
{
	id: 10,
	name: 'Piter Sunday',
	username: 'Babuaoc',
	email: 'babelonian@gmail.com',
},
{
	id: 1,
	name: 'Temitope Kazeem',
	username: 'TemmyT',
	email: 'temitoptaiwo@gmail.com',
},
{
	id: 11,
	name: 'Babatunde Oyemefun',
	username: 'Mefunlite',
	email: 'mefunlite12@gmail.com',
},
{
	id: 12,
	name: 'Babawale Tomori',
	username: 'Babcock',
	email: 'babcockians@gmail.com',
},
{
	id: 13,
	name: 'Fateemah Sadiq',
	username: 'fatimahsadiq',
	email: 'fatimahsadiq43@gmail.com',
},
{
	id: 14,
	name: 'Vivien Maduekwe',
	username: 'Gracious',
	email: 'viviengrace27@gmail.com',
},
{
	id: 15,
	name: 'vincent Chukwuebere',
	username: 'Balabablow',
	email: 'Balabablow@gmail.com',
},
{
	id: 16,
	name: 'Samad Badmus ',
	username: 'Gbolagas',
	email: 'gbolagas147@gmail.com',
},
{
	id: 17,
	name: 'Olayiwola Peter',
	username: 'olaoluwa',
	email: 'olaoluwapeter12@gmail.com',
},
{
	id: 18,
	name: 'James Musa',
	username: 'Mazdamarised',
	email: 'Mazdamarised@gmail.com',
},
{
	id: 19,
	name: 'Memunat Adebisi',
	username: 'Olabisi',
	email: 'memunatolabisi1@gmail.com',
},
{
	id: 20,
	name: 'Ajibola Olabisi',
	username: 'Graciously',
	email: 'ajibolagrace234@gmail.com',
},
{
	id: 1,
	name: 'Olawale Olayefa',
	username: 'Monterro',
	email: 'olawaleyefa@gmail.com',
},
{
	id: 2,
	name: 'Adeboye Emmnauel',
	username: 'Thomas',
	email: 'ademanuel@gmail.com',
},
{
	id: 3,
	name: 'Adeyemi John',
	username: 'vaquita',
	email: 'vaquitatech@gmail.com',
},
{
	id: 4,
	name: 'Adebayo Olamuyiwa',
	username: 'Bostons',
	email: 'muyiwabayo@gmail.com',
},
{
	id: 5,
	name: 'Adebola Adeola',
	username: 'Monterro',
	email: 'olawaleyefa@gmail.com',
},
{
	id: 6,
	name: 'Adeyanju Abimbola',
	username: 'Business',
	email: 'buyersales@gmail.com',
},
{
	id: 7,
	name: 'Pius Timothy',
	username: 'Blacklisted',
	email: 'Blacklisted@gmail.com',
},
{
	id: 8,
	name: 'Adijat Adebayo',
	username: 'Oritoke',
	email: 'adijatoritoke@gmail.com',
},
{
	id: 9,
	name: 'Muhammed Musa',
	username: 'Madhuka',
	email: 'hammedhukza@gmail.com',
},
{
	id: 10,
	name: 'Piter Sunday',
	username: 'Babuaoc',
	email: 'babelonian@gmail.com',
},
{
	id: 1,
	name: 'Temitope Kazeem',
	username: 'TemmyT',
	email: 'temitoptaiwo@gmail.com',
},
{
	id: 11,
	name: 'Babatunde Oyemefun',
	username: 'Mefunlite',
	email: 'mefunlite12@gmail.com',
},
{
	id: 12,
	name: 'Babawale Tomori',
	username: 'Babcock',
	email: 'babcockians@gmail.com',
},
{
	id: 13,
	name: 'Fateemah Sadiq',
	username: 'fatimahsadiq',
	email: 'fatimahsadiq43@gmail.com',
},
{
	id: 14,
	name: 'Vivien Maduekwe',
	username: 'Gracious',
	email: 'viviengrace27@gmail.com',
},
{
	id: 15,
	name: 'vincent Chukwuebere',
	username: 'Balabablow',
	email: 'Balabablow@gmail.com',
},
{
	id: 16,
	name: 'Samad Badmus ',
	username: 'Gbolagas',
	email: 'gbolagas147@gmail.com',
},
{
	id: 17,
	name: 'Olayiwola Peter',
	username: 'olaoluwa',
	email: 'olaoluwapeter12@gmail.com',
},
{
	id: 18,
	name: 'James Musa',
	username: 'Mazdamarised',
	email: 'Mazdamarised@gmail.com',
},
{
	id: 19,
	name: 'Memunat Adebisi',
	username: 'Olabisi',
	email: 'memunatolabisi1@gmail.com',
},
{
	id: 20,
	name: 'Ajibola Olabisi',
	username: 'Graciously',
	email: 'ajibolagrace234@gmail.com',
},
]